name: 🚀 Deploy main to Hostgator/Firebase
on: 
  push:
    branches:
      - main
jobs:
  web-deploy_hostgator:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: "${{ secrets.REACT_APP_API_KEY }}"
      REACT_APP_AUTH_DOMAIN: "${{ secrets.REACT_APP_AUTH_DOMAIN }}"
      REACT_APP_PROJECT_ID: "${{ secrets.REACT_APP_PROJECT_ID }}"
      REACT_APP_STORAGE_BUCKET: "${{ secrets.REACT_APP_STORAGE_BUCKET }}"
      REACT_APP_MESSAGING_SENDER_ID: "${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}"
      REACT_APP_APP_ID: "${{ secrets.REACT_APP_APP_ID }}"
      REACT_APP_MEASUREMENT_ID: "${{ secrets.REACT_APP_MEASUREMENT_ID }}"
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: personalfinance.dailysimpletools.com/
        local-dir: ./build/
  functions-deploy_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: 📥 Download deps
        working-directory: ./functions/
        run: npm install
      - name: 🚀 Deploy
        run: npx firebase-tools deploy --token "$FIREBASE_TOKEN" --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}